# Generated by Django 2.0 on 2020-03-03 09:00

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程名称')),
                ('desc', models.CharField(max_length=300, verbose_name='课程描述')),
                ('detail', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='课程详情')),
                ('is_tg', models.BooleanField(default=False, verbose_name='课程首页推广')),
                ('degree', models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], default='zj', max_length=5, verbose_name='视频级别')),
                ('learn_times', models.IntegerField(default=0, verbose_name='学习时长')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='课程类别')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/%Y/%m', verbose_name='封面图片')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击人数')),
                ('tag', models.CharField(blank=True, default='Python开发', max_length=20, null=True, verbose_name='课程标签')),
                ('kcxz', models.CharField(blank=True, max_length=50, null=True, verbose_name='课程须知')),
                ('xdaoshenm', models.CharField(blank=True, max_length=100, null=True, verbose_name='能学到什么？')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='课程机构')),
                ('kcjs_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='课程讲师')),
            ],
            options={
                'verbose_name': '课程详情',
                'verbose_name_plural': '课程详情',
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='附件名称')),
                ('download', models.FileField(max_length=150, upload_to='course/resource/%Y/%m', verbose_name='资源文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程名称')),
            ],
            options={
                'verbose_name': '课程附件',
                'verbose_name_plural': '课程附件',
                'db_table': 'CourseResource',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='章节名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程名称')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
                'db_table': 'Lesson',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='视频名称')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='视频资源地址')),
                ('video_time', models.IntegerField(blank=True, null=True, verbose_name='视频时长')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='章节名称')),
            ],
            options={
                'verbose_name': '视频资源',
                'verbose_name_plural': '视频资源',
                'db_table': 'Video',
            },
        ),
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '轮播课程',
                'verbose_name_plural': '轮播课程',
                'proxy': True,
                'indexes': [],
            },
            bases=('courses.course',),
        ),
    ]
